-- MySQL Script generated by MySQL Workbench
-- Fri Aug  1 13:57:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SGWA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SGWA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGWA` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------
USE `SGWA` ;

-- -----------------------------------------------------
-- Table `SGWA`.`acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`acesso` (
  `idAcesso` INT NOT NULL AUTO_INCREMENT,
  `acesso` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idAcesso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nomeCurso` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`utilizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`utilizador` (
  `idUtilizador` INT NOT NULL AUTO_INCREMENT,
  `nomeUtilizador` VARCHAR(45) NULL DEFAULT NULL,
  `nIdentificacao` VARCHAR(100) NULL,
  `emailUtilizador` VARCHAR(45) NULL DEFAULT NULL,
  `generoUtilizador` VARCHAR(45) NULL,
  `telefoneUtilizador` VARCHAR(45) NULL DEFAULT NULL,
  `moradaUtilizador` VARCHAR(45) NULL DEFAULT NULL,
  `perfilUtilizador` ENUM('Administrador', 'Aluno', 'Professor') NULL DEFAULT NULL,
  `senhaUtilizador` VARCHAR(255) NULL DEFAULT NULL,
  `idAcesso` INT NOT NULL,
  PRIMARY KEY (`idUtilizador`),
  INDEX `fk_utilizador_acesso1_idx` (`idAcesso` ASC) VISIBLE,
  UNIQUE INDEX `num_Identificacao_UNIQUE` (`nIdentificacao` ASC) VISIBLE,
  UNIQUE INDEX `telefoneUtilizador_UNIQUE` (`telefoneUtilizador` ASC) VISIBLE,
  UNIQUE INDEX `emailUtilizador_UNIQUE` (`emailUtilizador` ASC) VISIBLE,
  CONSTRAINT `fk_utilizador_acesso1`
    FOREIGN KEY (`idAcesso`)
    REFERENCES `SGWA`.`acesso` (`idAcesso`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `nomeProfessor` VARCHAR(60) NULL DEFAULT NULL,
  `nIdentificacaoProfessor` VARCHAR(45) NULL,
  `contactoProfessor` VARCHAR(45) NULL,
  `generoProfessor` VARCHAR(45) NULL DEFAULT NULL,
  `emailProfessor` VARCHAR(100) NULL DEFAULT NULL,
  `moradaProfessor` VARCHAR(45) NULL DEFAULT NULL,
  `dataNascProfessor` VARCHAR(60) NULL DEFAULT NULL,
  `dataContProfessor` VARCHAR(45) NULL DEFAULT NULL,
  `tipoContratoProfessor` ENUM('Efectivo', 'Temporário') NULL DEFAULT NULL,
  `idUtilizador` INT NOT NULL,
  PRIMARY KEY (`idProfessor`),
  INDEX `fk_professor_utilizador1_idx` (`idUtilizador` ASC) VISIBLE,
  UNIQUE INDEX `nIdentificacaoProfessor_UNIQUE` (`nIdentificacaoProfessor` ASC) VISIBLE,
  UNIQUE INDEX `emailProfessor_UNIQUE` (`emailProfessor` ASC) VISIBLE,
  UNIQUE INDEX `contactoProfessor_UNIQUE` (`contactoProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_professor_utilizador1`
    FOREIGN KEY (`idUtilizador`)
    REFERENCES `SGWA`.`utilizador` (`idUtilizador`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `nomeTurma` VARCHAR(50) NOT NULL,
  `salaTurma` VARCHAR(50) NULL DEFAULT NULL,
  `idCurso` INT NOT NULL,
  `idProfessor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idTurma`),
  INDEX `curso_id` (`idCurso` ASC) VISIBLE,
  INDEX `fk_turma_professor1_idx` (`idProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `SGWA`.`professor` (`idProfessor`),
  CONSTRAINT `turma_ibfk_1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `SGWA`.`curso` (`idCurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nomeAluno` VARCHAR(60) NULL DEFAULT NULL,
  `nIdentificacaoAluno` VARCHAR(45) NULL,
  `moradaAluno` VARCHAR(200) NULL DEFAULT NULL,
  `dataNascimentoAluno` VARCHAR(100) NULL DEFAULT NULL,
  `generoAluno` VARCHAR(40) NULL DEFAULT NULL,
  `fotoAluno` VARCHAR(255) NULL DEFAULT NULL,
  `responsavelAluno` VARCHAR(100) NULL DEFAULT NULL,
  `contactoResponsavelAluno` VARCHAR(20) NULL DEFAULT NULL,
  `anoIngressoAluno` VARCHAR(60) NULL DEFAULT NULL,
  `idUtilizador` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `idTurma` INT NOT NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `fk_aluno_utilizador1_idx` (`idUtilizador` ASC) VISIBLE,
  INDEX `fk_aluno_curso1_idx` (`idCurso` ASC) VISIBLE,
  UNIQUE INDEX `nIdentificacaoAluno_UNIQUE` (`nIdentificacaoAluno` ASC) VISIBLE,
  UNIQUE INDEX `contactoResponsavelAluno_UNIQUE` (`contactoResponsavelAluno` ASC) VISIBLE,
  INDEX `fk_aluno_turma1_idx` (`idTurma` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `SGWA`.`curso` (`idCurso`),
  CONSTRAINT `fk_aluno_utilizador1`
    FOREIGN KEY (`idUtilizador`)
    REFERENCES `SGWA`.`utilizador` (`idUtilizador`),
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`idTurma`)
    REFERENCES `SGWA`.`turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`disciplina` (
  `idDisciplina` INT NOT NULL AUTO_INCREMENT,
  `nomeDisciplina` VARCHAR(100) NOT NULL,
  `classeDisciplina` VARCHAR(40) NULL,
  `idCurso` INT NOT NULL,
  `idProfessor` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  INDEX `curso_id` (`idCurso` ASC) VISIBLE,
  INDEX `fk_disciplina_professor1_idx` (`idProfessor` ASC) VISIBLE,
  CONSTRAINT `disciplina_ibfk_1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `SGWA`.`curso` (`idCurso`),
  CONSTRAINT `fk_disciplina_professor1`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `SGWA`.`professor` (`idProfessor`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`documento` (
  `idDocumento` INT NOT NULL AUTO_INCREMENT,
  `idAluno` INT NOT NULL,
  `tipoDocumento` ENUM('Declaração', 'Boletim', 'Certificado') NOT NULL,
  `estadoDocumento` ENUM('Aceite', 'Recusado', 'Em Validação') NULL,
  `dataEmissaoDocumento` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idDocumento`),
  INDEX `aluno_id` (`idAluno` ASC) VISIBLE,
  CONSTRAINT `documento_ibfk_1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SGWA`.`aluno` (`idAluno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `tituloEvento` VARCHAR(45) NOT NULL,
  `dataEvento` VARCHAR(45) NOT NULL,
  `horaInicio` VARCHAR(45) NOT NULL,
  `horaFim` VARCHAR(45) NOT NULL,
  `localEvento` VARCHAR(45) NOT NULL,
  `responsavelEvento` VARCHAR(45) NOT NULL,
  `tipoEvento` ENUM('Prova', 'Atividade', 'Reunião', 'Apresentação') NOT NULL,
  `idUtilizador` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_evento_utilizador1_idx` (`idUtilizador` ASC) VISIBLE,
  INDEX `fk_evento_curso1_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_evento_curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `SGWA`.`curso` (`idCurso`),
  CONSTRAINT `fk_evento_utilizador1`
    FOREIGN KEY (`idUtilizador`)
    REFERENCES `SGWA`.`utilizador` (`idUtilizador`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `idTurma` INT NOT NULL,
  `idDisciplina` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `diasSemanaHorario` ENUM('Segunda-Feira', 'Terça-Feira', 'Quarta-Feira', 'Quinta-Feira', 'Sexta-Feira', 'Sábado', 'Domingo') NULL DEFAULT NULL,
  `horaInicioHorario` TIME NOT NULL,
  `horaFimHorario` TIME NOT NULL,
  `salaHorario` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idHorario`),
  INDEX `turma_id` (`idTurma` ASC) VISIBLE,
  INDEX `disciplina_id` (`idDisciplina` ASC) VISIBLE,
  INDEX `fk_horario_curso1_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `horario_ibfk_1`
    FOREIGN KEY (`idTurma`)
    REFERENCES `SGWA`.`turma` (`idTurma`),
  CONSTRAINT `horario_ibfk_2`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `SGWA`.`disciplina` (`idDisciplina`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`matricula` (
  `idMatricula` INT NOT NULL AUTO_INCREMENT,
  `idAluno` INT NOT NULL,
  `idTurma` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `dataMatricula` VARCHAR(60) NULL DEFAULT NULL,
  `estadoMatricula` ENUM('Activa', 'Cancelada', 'Trancada') NULL DEFAULT NULL,
  `classeMatricula` VARCHAR(45) NULL,
  `periodoMatricula` VARCHAR(45) NULL,
  PRIMARY KEY (`idMatricula`),
  INDEX `aluno_id` (`idAluno` ASC) VISIBLE,
  INDEX `turma_id` (`idTurma` ASC) VISIBLE,
  INDEX `fk_matricula_curso1_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `SGWA`.`curso` (`idCurso`),
  CONSTRAINT `matricula_ibfk_1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SGWA`.`aluno` (`idAluno`),
  CONSTRAINT `matricula_ibfk_2`
    FOREIGN KEY (`idTurma`)
    REFERENCES `SGWA`.`turma` (`idTurma`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`nota` (
  `idNota` INT NOT NULL AUTO_INCREMENT,
  `idAluno` INT NOT NULL,
  `idDisciplina` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `valorNota` VARCHAR(100) NULL DEFAULT NULL,
  `dataAvaliacaoNota` VARCHAR(60) NULL DEFAULT NULL,
  `tipoAvaliacaoNota` ENUM('Avaliação Continua', 'Prova do professor', 'Prova trimestral', 'Exame') NULL DEFAULT NULL,
  `tipoNota` ENUM('MAC', "NPP", "NPT") NULL,
  `trimestreNota` ENUM("1º Trimestre", "2º Trimestre", "3º Trimestre") NULL,
  PRIMARY KEY (`idNota`),
  INDEX `aluno_id` (`idAluno` ASC) VISIBLE,
  INDEX `disciplina_id` (`idDisciplina` ASC) VISIBLE,
  INDEX `fk_nota_curso1_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_nota_curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `SGWA`.`curso` (`idCurso`),
  CONSTRAINT `nota_ibfk_1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SGWA`.`aluno` (`idAluno`),
  CONSTRAINT `nota_ibfk_2`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `SGWA`.`disciplina` (`idDisciplina`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SGWA`.`notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGWA`.`notificacoes` (
  `idNotificacoes` INT NOT NULL AUTO_INCREMENT,
  `tipoNotificacoes` VARCHAR(100) NULL DEFAULT NULL,
  `mensagemNotificacoes` VARCHAR(255) NULL DEFAULT NULL,
  `dataNotificacoes` DATETIME NULL DEFAULT NULL,
  `lidaNotificacoes` TINYINT NULL DEFAULT NULL,
  `idUtilizador` INT NOT NULL,
  PRIMARY KEY (`idNotificacoes`),
  INDEX `fk_notificacoes_utilizador1_idx` (`idUtilizador` ASC) VISIBLE,
  CONSTRAINT `fk_notificacoes_utilizador1`
    FOREIGN KEY (`idUtilizador`)
    REFERENCES `SGWA`.`utilizador` (`idUtilizador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO acesso (acesso) VALUES ("Estrela@?.1000");

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
